### ISSUE TITLE
Improve points-giving syntax

### ISSUE THREAD

**Issue by simshadows** [waream2/cb-bots#23]
Currently, doing an @-mention in the Discord UI will automatically add a space after the mention (at least for me on Windows/Linux/Mac), which means that the user will need to consciously remove the space to add the suffix. This is a usability issue that I think should be looked into to make it more intuitive.

Though, I think the course of action for now will be to see if people run into this issue and see what they think.

**Comment by waream2** [comment]
Im with you to keep an eye on it and see if it becomes an issue. Although, I think i agree that it's a bit awkward to have to eliminate the space to add the suffix.

I think im on-board to just fix with however, it doesnt seem like a priority compared to the other issues.

**Comment by Claudi0-V** [comment]
since this change would be trivial and I've seen 2 different people having this problem, I'm in favor of changing it
