### ISSUE TITLE
Change invalid command handling

### ISSUE THREAD

**Issue by simshadows** [waream2/cb-bots#27]
Currently (as far as I can tell), all invalid commands are replied to in the same channel of invocation:

![image](https://user-images.githubusercontent.com/13399999/157825375-d564c37d-64ad-4756-a49f-4dcfd457e470.png)

I think it's worth considering changing to a more silent behaviour.

My suggestion:

- The bot should not give feedback for invalid command __*names*__.
    - Example: `!poiints` will not be given feedback by the bot.
- Invalid command __*arguments*__ should be replied to with an error message in the same channel of invocation.
    - We don't actually have any such commands (except maybe the suffix-syntax command). I'm suggesting this for the future.
    - To illustrate this behaviour though, let's suppose we have `!random` command.
        - Suppose `!random 10` is a command to dice roll from 1 to 10.
        - Suppose `!random 9999999999999999999999999999999999` is an invalid command because the number is too big.
        - That invalid command is an example of such a command invocation that I think should be given feedback to the user.
- We should also fix the MD injection vulnerability with these error messages. (See the comments for a demo.)

Alternative ideas:

- Maybe some variation of using DMs?

---

*(This issue originates from the comments of #24)*

**Comment by Claudi0-V** [comment]
I just checked and if you write code like `"a" !== "b"` it will see as if is a command, so even normal code written could be interpreted by the bot. therefore I also think that we should change this behavior

**Comment by simshadows** [comment]
![image](https://user-images.githubusercontent.com/13399999/158061124-88def785-12a0-4618-bcf0-778a773946e9.png)

🤔

**Comment by simshadows** [comment]
Side-note: the error message is also vulnerable to MD injection

![image](https://user-images.githubusercontent.com/13399999/158318949-72568b43-80b8-41c4-a856-47f38458550e.png)

**Comment by Claudi0-V** [comment]
just to add to the issue for documentation purposes, @doulovera pointed out that any message containing `!` in the beginning will trigger the command, even if is in a codeblock.
![image](https://user-images.githubusercontent.com/30845840/158656363-2b880035-941f-4f64-ab69-a807c37da58a.png)

Due to this, I'm in favor of @doulovera proposal of only triggering a command if is in the beginning of a message.
