### ISSUE TITLE
DB don't saves data

### ISSUE THREAD

**Issue by Claudi0-V** [waream2/cb-bots#30]
According to @doulovera heroku deletes files after 24h. Due to that the points are being deleted. therefore we need to use a different way of saving the data that is not a local db stored on heroku

**Comment by waream2** [comment]
@Claudi0-V ahh yeah, thats very stupid. Seems like we may need to move over to a more persistence data option. Any suggestions on a solution. I think we'd want to stay noSQL because that's our current data structure.

**Comment by Claudi0-V** [comment]
i have no knowledge regarding S3, so i'll let this one for you and the others
